services:
  wg-loom:
    container_name: wg-loom
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - wg-loom-database
    network_mode: host
    volumes:
      - /root/backup/wireguard/interfaces:/etc/wireguard/
      - /root/wgloom:/wgloom/
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  # config postgres data base
  wg-loom-database:
    container_name: wg-loom-database
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wg-loom-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

  db_admin:
    container_name: db-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hossein@faraji.com
      - PGADMIN_DEFAULT_PASSWORD=Hossein*(!^
#    network_mode: host


volumes:
  postgres_data:
