services:
  wg-loom:
    container_name: wg-loom
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - wg-loom-database
#    network_mode: host
    volumes:
      - /root/backup/wireguard/interfaces:/etc/wireguard/
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  # config postgres data base
  wg-loom-database:
    container_name: wg-loom-database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wg-loom-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
#    network_mode: host5

  db_admin:
    container_name: db-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=hossein@faraji.com
      - PGADMIN_DEFAULT_PASSWORD=Hossein*(!^
#    network_mode: host


volumes:
  postgres_data:
