"""add peer config

Revision ID: 4d440970891a
Revises: 7c643c6626eb
Create Date: 2025-03-23 16:39:52.713779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d440970891a'
down_revision: Union[str, None] = '7c643c6626eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('token', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'peers', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peers', type_='unique')
    op.drop_column('peers', 'token')
    # ### end Alembic commands ###
