"""update peer table

Revision ID: 731f71593277
Revises: c0dff24614c5
Create Date: 2025-03-22 16:29:22.439634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '731f71593277'
down_revision: Union[str, None] = 'c0dff24614c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'interfaces', ['listen_port'])
    op.create_unique_constraint(None, 'interfaces', ['private_key'])
    op.create_unique_constraint(None, 'interfaces', ['ip_address'])
    op.create_unique_constraint(None, 'interfaces', ['public_key'])
    op.create_unique_constraint(None, 'peers', ['pre_shared_key'])
    op.create_unique_constraint(None, 'peers', ['private_key'])
    op.create_unique_constraint(None, 'peers', ['public_key'])
    op.drop_column('peers', 'allowedIPs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('allowedIPs', postgresql.INET(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'peers', type_='unique')
    op.drop_constraint(None, 'peers', type_='unique')
    op.drop_constraint(None, 'peers', type_='unique')
    op.drop_constraint(None, 'interfaces', type_='unique')
    op.drop_constraint(None, 'interfaces', type_='unique')
    op.drop_constraint(None, 'interfaces', type_='unique')
    op.drop_constraint(None, 'interfaces', type_='unique')
    # ### end Alembic commands ###
