"""reletions for tables

Revision ID: 905052b73058
Revises: 9f888cff1b48
Create Date: 2025-03-20 16:15:07.797791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905052b73058'
down_revision: Union[str, None] = '9f888cff1b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_addresses',
    sa.Column('ip', sa.String(length=17), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    op.add_column('peers', sa.Column('interface_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'peers', 'interfaces', ['interface_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peers', type_='foreignkey')
    op.drop_column('peers', 'interface_id')
    op.drop_table('ip_addresses')
    # ### end Alembic commands ###
