"""config peer table

Revision ID: 96a77bfc4089
Revises: 731f71593277
Create Date: 2025-03-23 14:30:24.854356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96a77bfc4089'
down_revision: Union[str, None] = '731f71593277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('total_volume', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('expire_time', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('upload_volume', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('last_total_received_volume', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('last_download_volume', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('last_upload_volume', sa.BIGINT(), nullable=True))
    op.add_column('peers', sa.Column('on_hold_expire_duration', sa.BIGINT(), nullable=True))
    op.drop_column('peers', 'addresses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('addresses', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('peers', 'on_hold_expire_duration')
    op.drop_column('peers', 'last_upload_volume')
    op.drop_column('peers', 'last_download_volume')
    op.drop_column('peers', 'last_total_received_volume')
    op.drop_column('peers', 'upload_volume')
    op.drop_column('peers', 'expire_time')
    op.drop_column('peers', 'total_volume')
    # ### end Alembic commands ###
