"""update interface

Revision ID: 9f888cff1b48
Revises: 
Create Date: 2025-03-20 15:11:26.441525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f888cff1b48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interfaces',
    sa.Column('name', sa.String(length=34), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('save_config', sa.Boolean(), nullable=True),
    sa.Column('pre_up', sa.String(), nullable=True),
    sa.Column('post_up', sa.String(), nullable=True),
    sa.Column('pre_down', sa.String(), nullable=True),
    sa.Column('post_down', sa.String(), nullable=True),
    sa.Column('listen_port', sa.Integer(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('public_key', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', name='interfacestatus'), nullable=True),
    sa.Column('upload_percent', sa.Float(), nullable=True),
    sa.Column('download_percent', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interfaces_name'), 'interfaces', ['name'], unique=True)
    op.create_table('peers',
    sa.Column('name', sa.String(length=34), nullable=True),
    sa.Column('public_key', sa.String(length=512), nullable=True),
    sa.Column('private_key', sa.String(length=512), nullable=True),
    sa.Column('pre_shared_key', sa.String(length=512), nullable=True),
    sa.Column('allowedIPs', postgresql.INET(), nullable=True),
    sa.Column('addresses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('dns', sa.String(length=50), nullable=True),
    sa.Column('mut', sa.Integer(), nullable=True),
    sa.Column('persistent_keep_alive', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disabled', 'limited', 'expired', 'on_hold', name='userstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peers_name'), 'peers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('user_name', sa.String(length=34), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_peers_name'), table_name='peers')
    op.drop_table('peers')
    op.drop_index(op.f('ix_interfaces_name'), table_name='interfaces')
    op.drop_table('interfaces')
    # ### end Alembic commands ###
