"""update reletions

Revision ID: c0dff24614c5
Revises: 905052b73058
Create Date: 2025-03-20 16:22:22.146629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dff24614c5'
down_revision: Union[str, None] = '905052b73058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_addresses', sa.Column('interface_id', sa.Integer(), nullable=True))
    op.add_column('ip_addresses', sa.Column('peer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ip_addresses', 'interfaces', ['interface_id'], ['id'])
    op.create_foreign_key(None, 'ip_addresses', 'peers', ['peer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_addresses', type_='foreignkey')
    op.drop_constraint(None, 'ip_addresses', type_='foreignkey')
    op.drop_column('ip_addresses', 'peer_id')
    op.drop_column('ip_addresses', 'interface_id')
    # ### end Alembic commands ###
