"""add peer config

Revision ID: cd15d8051e12
Revises: 3b7ca5a008ba
Create Date: 2025-03-23 17:20:48.230619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd15d8051e12'
down_revision: Union[str, None] = '3b7ca5a008ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('end_point_allowed_ips', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peers', 'end_point_allowed_ips')
    # ### end Alembic commands ###
